using Dapper.Contrib.Extensions;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.AuthServer.Database
{
    [TableName("groups_servers")]
    [Table("groups_servers")]
    public class UserGroupServer : DbObject<UserGroupServer>, IAutoGeneratedRecord
    {
        [PrimaryKey("Id")]
        [Key]
        public int Id
        {
            get;
            set;
        }

        public int UserId
        {
            get;
            set;
        }

        public int ServerId
        {
            get;
            set;
        }
    }
}