using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Database.Items.Templates;
using Stump.Server.WorldServer.Database.Monsters;
using Stump.Server.WorldServer.Game.Actors.RolePlay.Monsters;
using Stump.Server.WorldServer.Game.Items;

namespace ArkalysPlugin.Daily
{
    public class DailyObjectiveRelator
    {
        public static string FetchQuery = "SELECT * FROM plugin_daily_objectives";
    }

    [TableName("plugin_daily_objectives")]
    public class DailyObjectiveRecord : IAutoGeneratedRecord
    {
        private MonsterTemplate m_monster;
        private ItemTemplate m_item;

        public int Id
        {
            get;
            set;
        }


        public int? MonsterId
        {
            get;
            set;
        }

        public MonsterTemplate Monster => MonsterId.HasValue ? (m_monster ?? (m_monster = MonsterManager.Instance.GetTemplate(MonsterId.Value))) : null;

        public int? ItemId
        {
            get;
            set;
        }
        
        public ItemTemplate Item => ItemId.HasValue ? (m_item ?? (m_item = ItemManager.Instance.TryGetTemplate(ItemId.Value))) : null;

        public string Name => Monster?.Name ?? (Item?.Name ?? "(INVALID)");

        public int? MapId
        {
            get;
            set;
        }

        public int Amount
        {
            get;
            set;
        }

        public int MinLevel
        {
            get;
            set;
        }

        public int MaxLevel
        {
            get;
            set;
        }

        [DefaultSetting(1.0)]
        public double Difficulty
        {
            get;
            set;
        }
    }
}